#!/usr/bin/env python

import os
import requests
import pipes
import sys
release=requests.get("https://api.github.com/repos/iggyvolz/korra-dl/releases?access_token=85abd30733ad6da19fffeb9e34bb780fe2de4810")
asset=requests.get(release.json()[0]["assets_url"]+"?access_token=85abd30733ad6da19fffeb9e34bb780fe2de4810")
url=asset.json()[0]["browser_download_url"]
version=release.json()[0]["tag_name"]
os.system("curl -L "+pipes.quote(url)+">/usr/local/bin/korra-dl")
sys.exit("Installed latest version of korra-dl.  To update, type (sudo) korra-dl -U.")
