#!/usr/bin/env python

import os
import requests
import pipes
import sys
release=requests.get("https://api.github.com/repos/iggyvolz/korra-dl/releases")
asset=requests.get(release.json()[0]["assets_url"])
url=asset.json()[0]["browser_download_url"]
version=release.json()[0]["tag_name"]
os.system("curl -L "+pipes.quote(url)+">/usr/local/bin/korra-dl && chmod +x /usr/local/bin/korra-dl")
sys.exit("Installed latest version of korra-dl.  To update, type (sudo) korra-dl -U.")
