#!/usr/bin/env python

import sys
import os
import requests
import string
from xml.etree import ElementTree
if int(sys.argv[2])>7:
  sys.exit ("ERROR: Invalid output type.  Use types 1-7, see iggyvolz.github.io/korra-dl/types.html for details")
episodehash={
211:"4edc8504-22f2-11e4-b48f-0026b9414f30"
  }.get(int(sys.argv[1]),None)
if episodehash is None:
  sys.exit("ERROR: Invalid episode number.  Episode numbers should be in the following format: Season number (1-3) followed by episode number (01-14)")
r=requests.get("http://media-utils-api.mtvnservices.com/services/MediaGenerator/mgid:arc:video:nick.com:"+episodehash+"?arcStage=live")
url=ElementTree.XML(r.text)[0][0][int(sys.argv[2])-1][0].text
os.system("ffmpeg -i "+url+" "+sys.argv[3])
